# Site settings
project: losmejorescortos
baseurl: /losmejorescortos.bundle
email: manferwebs@gmail.com
github_username: manfer
bootstrap_theme: slate

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

